### ISSUE TITLE
How to insert a csv file into mysql without headers?

### ISSUE THREAD

**Issue by stevenluoxiaohua** [ZJONSSON/node-etl#31]
I want insert a csv file into mysql table, this file without headers

**Comment by ZJONSSON** [comment]
There is a simple example in the docs [here](https://github.com/ZJONSSON/node-etl#mysqlexecute)

Here is another version:
```js
fs.createReadStream('test,csv')
  .pipe(etl.csv())
  .pipe(etl.mysql.upsert(client,'myschema','mytable',{maxBufffer: 100000))
```

the `etl.mysql.upsert` is  syntax sugar for a sub-chain of  `etl.mysql.script` that adds incoming packet to a bulk upsert command (until maxbuffer is reached) and `etl.execute` which executes all incoming sql commands (the bulkupdates scripted in previous step).

It's worth noting that the `etl.mysql.script` fetches all the column names from the table schema and includes fields from incoming packets that match the database fields (case sensitive)

**Comment by stevenluoxiaohua** [comment]
Thanks for you reply. 
Now, I have anther problem.
the csv-write-stream is so slow when I convert a large json object (over 2,000,000 rows).

PS:This project is very valuable, thanks for share.

**Comment by ZJONSSON** [comment]
You should try:
* Increase the maxBuffer (builds larger queries)
* Make sure that your client is the [mysql pool](https://github.com/mysqljs/mysql#pooling-connections) with a nice connectionLimit for parallel upserts
