### ISSUE TITLE
Migrating to class syntax

### ISSUE THREAD

**Issue by dennismphil** [ZJONSSON/node-etl#69]
Will you be open to migrating to the ES6 `class` syntax. Would like to hear your thoughts on the following sample piece of code taken from `lib/postgres/execute.js` before I start doing a full blown PR.

Eg:

### Existing Code

```
const Postgres = require('./postgres');
const util = require('util');

function Execute(pool,options) {
  if (!(this instanceof Execute))
    return new Execute(pool,options);

  options = options || {};
  Postgres.call(this,pool,options);

}

util.inherits(Execute,Postgres);

Execute.prototype._fn = function(d,cb) {
  // TODO make transaction or use {maxBuffer:1} in options
  //console.log(d);
  return this.query(d,cb)
    .then(d => this.options.pushResult && d || undefined);
};

module.exports = Execute;
```

### Proposed Changes
![new code](https://user-images.githubusercontent.com/4141366/38714702-466db7e4-3e8c-11e8-8792-bd9fc375efea.png)

### Passes the test
```
node test/postgres-test.js
TAP version 13
# Subtest: postgres
    # Subtest: inserts
        ok 1 - returns correct length
        1..1
    ok 1 - inserts # time=27.359ms

    # Subtest: and records are verified
        ok 1 - records verified
        1..1
    ok 2 - and records are verified # time=3.427ms

    # Subtest: streaming
        ok 1 - work
        1..1
    ok 3 - streaming # time=3.507ms

    1..3
ok 1 - postgres # time=56.602ms

1..1
# time=63.281ms
```

**Comment by ZJONSSON** [comment]
Thanks @dennismphil I'm all for it, provided we still retain backwards compatibility for calling the object without `new`, i.e.:
```js
  if (!(this instanceof Execute))
    return new Execute(pool,options);
```
This would make sure we don't break anything.

**Comment by dennismphil** [comment]
Yes I made sure this will still work without needing a `new`

If you notice the last line of the new code, we are exporting the instance of the class
`module.exports = (...params) => new Execute(...params)` which will ensure backward compatibility.
